// =============================================
// SocialAudit.be - Donnees de demonstration
// Fiches d'audit pre-remplies pour tests et demo
// =============================================

import { DemoFiche } from './types';

export const DEMO: DemoFiche[] = [
  {id:"lejeune",label:"Marc Lejeune",sub:"Continu 5 eq. - Juin 2024",tag:"NON CONFORME",tc:"#C0392B",score:18,ficheYear:2024,ficheMode:"retro",ficheType:"direct",
   analyse:{worker:{name:"Marc Lejeune",cp:"CP 129",regime:"Continu 5 equipes",anciennete:"11 ans"},conformite_globale:"NON CONFORME",score:18,
    risque_financier_estime:"44.460 euros (ce travailleur uniquement)",
    passif_par_travailleur:[{poste:"Prime nuit semaine manquante",montant_mensuel:"209 euros",montant_total_5ans:"12.540 euros"},{poste:"Sursalaire dimanche absent",montant_mensuel:"322 euros",montant_total_5ans:"19.320 euros"},{poste:"Sursalaire feries absent",montant_mensuel:"198 euros",montant_total_5ans:"11.880 euros"},{poste:"Base heures sup incorrecte",montant_mensuel:"12 euros",montant_total_5ans:"720 euros"}],
    alertes:[{type:"CRITIQUE",titre:"Taux globalise non decompose",detail:"Taux 24.80euros/h sans decomposition. CCT 2025-2026 prevoit une periode de transition.",montant_estime:"22.540 euros",base_legale:"CCT Burgo + Loi 1971 art.29",niveau:"CCT-ENTREPRISE"},{type:"CRITIQUE",titre:"Sursalaire dim/feries absent",detail:"13h dim + 8h feries sans sursalaire +100%.",montant_estime:"520 euros/mois",base_legale:"Loi 16/03/1971 art.29",niveau:"LOI"},{type:"ATTENTION",titre:"Formation insuffisante",detail:"2j sur 5j requis en 2024.",montant_estime:"-",base_legale:"Loi Deal emploi 03/10/2022",niveau:"LOI"}],
    points_conformes:["ONSS calcule correctement","Heures totales coherentes"],
    recommandations:["Decomposer le taux globalise","Ajouter sursalaires dim/feries","Regulariser 38h recuperation"],
    note_contexte:"CCT Burgo: transition salariale en cours. Deglobalisation prevue 01/01/2027.",_confidence:85}},
  {id:"renard",label:"Sophie Renard",sub:"Semi-continu - Jan. 2025",tag:"RISQUE MODERE",tc:"#E67E22",score:52,ficheYear:2025,ficheMode:"retro",ficheType:"direct",
   analyse:{worker:{name:"Sophie Renard",cp:"CP 129",regime:"Semi-continu 3 equipes",anciennete:"6 ans"},conformite_globale:"RISQUE MODERE",score:52,
    risque_financier_estime:"768 euros (ce travailleur uniquement)",
    passif_par_travailleur:[{poste:"Indexation CP 129 2024 non appliquee (+2.12%)",montant_mensuel:"64 euros",montant_total_5ans:"768 euros"}],
    alertes:[{type:"ATTENTION",titre:"Indexation 2024 non appliquee",detail:"Taux 19.40 inchange. Du: 19.81euros/h. Manque 64 euros/mois.",montant_estime:"64 euros/mois",base_legale:"CP 129 indexation trimestrielle",niveau:"CP"},{type:"ATTENTION",titre:"Formation insuffisante 2024",detail:"3j sur 5j requis.",montant_estime:"-",base_legale:"Loi Deal emploi 03/10/2022",niveau:"LOI"}],
    points_conformes:["Plan formation 2025 depose","ONSS correct","Heures sup correctes"],
    recommandations:["Corriger taux: 19.81euros/h","Regulariser ecart 384 euros"],
    note_contexte:"Indexation manquante souvent invisible. Facile a regulariser.",_confidence:88}},
  {id:"fontaine",label:"Didier Fontaine",sub:"Continu 5 eq. - Mars 2027",tag:"CONFORME",tc:"#1A7A4A",score:97,ficheYear:2027,ficheMode:"preventif",ficheType:"direct",
   analyse:{worker:{name:"Didier Fontaine",cp:"CP 129",regime:"Continu 5 equipes",anciennete:"14 ans"},conformite_globale:"PRETE A EMETTRE",score:97,
    risque_financier_estime:"0 euros - fiche conforme",passif_par_travailleur:[],alertes:[],
    points_conformes:["Taux base 18.20euros/h correct","Primes decomposees CCT art.3","Sursalaire dim +100% sur taux BASE","Formation 5j planifiee","Tickets 10euros conformes CCT"],
    recommandations:["Maintenir ce niveau","Verifier indexation prochain trimestre"],
    note_contexte:"Fiche exemplaire post-deglobalisation.",_confidence:98}},
  {id:"martin2027",label:"Julie Martin",sub:"Journee fixe - Jan. 2027",tag:"RISQUE MODERE",tc:"#E67E22",score:61,ficheYear:2027,ficheMode:"preventif",ficheType:"direct",
   analyse:{worker:{name:"Julie Martin",cp:"CP 129",regime:"Journee fixe",anciennete:"3 ans"},conformite_globale:"RISQUE MODERE",score:61,_year:2027,
    risque_financier_estime:"1.920 euros (ce travailleur uniquement)",
    passif_par_travailleur:[{poste:"Tickets restaurant sous-evalues (8 vs 10euros)",montant_mensuel:"32 euros",montant_total_5ans:"384 euros"},{poste:"Indexation CP 129 jan 2027 non appliquee",montant_mensuel:"128 euros",montant_total_5ans:"1.536 euros"}],
    alertes:[{type:"ATTENTION",titre:"Tickets restaurant 8euros au lieu de 10euros",detail:"CCT Burgo art.5 prevoit 10euros depuis 01/06/2026. Fiche encore a 8euros.",montant_estime:"32 euros/mois",base_legale:"CCT Burgo 2025-2026 art.5",niveau:"CCT-ENTREPRISE"},{type:"ATTENTION",titre:"Indexation jan 2027 non appliquee",detail:"Nouvelle indexation CP 129 applicable depuis 01/01/2027 non repercutee.",montant_estime:"128 euros/mois",base_legale:"CP 129 indexation trimestrielle",niveau:"CP"}],
    points_conformes:["Formation 5j planifiee","ONSS calcule correctement","Heures standard conformes"],
    recommandations:["Corriger tickets a 10euros","Appliquer indexation jan 2027"],
    note_contexte:"Deux corrections mineures post-deglobalisation. Facile a regulariser.",_confidence:90}},
  {id:"dupont2027",label:"Pierre Dupont",sub:"Continu 5 eq. - Fev. 2027",tag:"NON CONFORME",tc:"#C0392B",score:22,ficheYear:2027,ficheMode:"preventif",ficheType:"direct",
   analyse:{worker:{name:"Pierre Dupont",cp:"CP 129",regime:"Continu 5 equipes",anciennete:"7 ans"},conformite_globale:"NON CONFORME",score:22,_year:2027,
    risque_financier_estime:"38.400 euros (ce travailleur uniquement)",
    passif_par_travailleur:[{poste:"Prime nuit CCT n49 non appliquee (1.51euros/h)",montant_mensuel:"157 euros",montant_total_5ans:"1.884 euros"},{poste:"Sursalaire dimanche base globalise",montant_mensuel:"298 euros",montant_total_5ans:"17.880 euros"},{poste:"Sursalaire feries base globalise",montant_mensuel:"187 euros",montant_total_5ans:"11.220 euros"},{poste:"Base heures sup globalise non decompose",montant_mensuel:"124 euros",montant_total_5ans:"7.416 euros"}],
    alertes:[{type:"CRITIQUE",titre:"Prime nuit CCT n49 absente",detail:"Minimum 1.51euros/h obligatoire depuis jan 2026 pour heures entre 22h-6h. Absent de la fiche.",montant_estime:"157 euros/mois",base_legale:"CCT interprofessionnelle n49 - jan 2026",niveau:"LOI"},{type:"CRITIQUE",titre:"Sursalaires dim/feries sur base globalise",detail:"Taux globalise encore utilise en fev 2027 post-deglobalisation. Sursalaires doivent etre calcules sur taux BASE uniquement.",montant_estime:"485 euros/mois",base_legale:"Loi 16/03/1971 art.29 + CCT Burgo art.2",niveau:"CCT-ENTREPRISE"},{type:"ATTENTION",titre:"Deglobalisation non appliquee",detail:"CCT Burgo prevoyait transition au 01/01/2027. Fiche de fev 2027 encore en mode globalise.",montant_estime:"-",base_legale:"CCT Burgo 2025-2026 art.2",niveau:"CCT-ENTREPRISE"}],
    points_conformes:["ONSS calcule sur bons montants","Tickets 10euros conformes","Formation 5j OK"],
    recommandations:["Appliquer deglobalisation immediatement","Ajouter prime nuit 1.51euros/h","Recalculer sursalaires sur taux BASE"],
    note_contexte:"Fiche post-deglobalisation non conforme. La CCT Burgo imposait la transition au 01/01/2027.",_confidence:87}},
  {id:"lejeune2026",label:"Marc Lejeune",sub:"Continu 5 eq. - Dec. 2026",tag:"NON CONFORME",tc:"#C0392B",score:25,ficheYear:2026,ficheMode:"retro",ficheType:"direct",
   analyse:{worker:{name:"Marc Lejeune",cp:"CP 129",regime:"Continu 5 equipes",anciennete:"13 ans"},conformite_globale:"NON CONFORME",score:25,_year:2026,
    risque_financier_estime:"41.520 euros (ce travailleur uniquement)",
    passif_par_travailleur:[{poste:"Sursalaire dimanche base globalise",montant_mensuel:"322 euros",montant_total_5ans:"19.320 euros"},{poste:"Sursalaire feries base globalise",montant_mensuel:"198 euros",montant_total_5ans:"11.880 euros"},{poste:"Prime nuit CCT n49 absente depuis jan 2026",montant_mensuel:"157 euros",montant_total_5ans:"1.884 euros"},{poste:"Base heures sup incorrecte",montant_mensuel:"12 euros",montant_total_5ans:"720 euros"}],
    alertes:[{type:"CRITIQUE",titre:"Prime nuit 1.51euros/h absente",detail:"CCT n49 impose 1.51euros/h depuis jan 2026 pour heures 22h-6h. Absent de la fiche dec 2026.",montant_estime:"157 euros/mois",base_legale:"CCT interprofessionnelle n49 jan 2026",niveau:"LOI"},{type:"CRITIQUE",titre:"Sursalaires encore sur base globalise",detail:"Taux globalise toujours utilise en dec 2026. Deglobalisation prevue 01/01/2027.",montant_estime:"520 euros/mois",base_legale:"Loi 16/03/1971 art.29",niveau:"LOI"},{type:"ATTENTION",titre:"Tickets encore a 8euros",detail:"CCT Burgo art.5 prevoit 10euros depuis 01/06/2026. Dec 2026 encore a 8euros.",montant_estime:"24 euros/mois",base_legale:"CCT Burgo 2025-2026 art.5",niveau:"CCT-ENTREPRISE"}],
    points_conformes:["Formation 5j completee","ONSS correct"],
    recommandations:["Ajouter prime nuit 1.51euros/h","Corriger tickets a 10euros","Preparer deglobalisation jan 2027"],
    note_contexte:"Derniere fiche avant deglobalisation. Prime nuit CCT n49 manquante depuis jan 2026.",_confidence:88}},
  {id:"lambert2022",label:"Henri Lambert",sub:"Continu 5 eq. - Oct. 2022",tag:"NON CONFORME",tc:"#C0392B",score:20,ficheYear:2022,ficheMode:"retro",ficheType:"direct",
   analyse:{worker:{name:"Henri Lambert",cp:"CP 129",regime:"Continu 5 equipes",anciennete:"8 ans"},conformite_globale:"NON CONFORME",score:20,_year:2022,
    risque_financier_estime:"31.560 euros (ce travailleur uniquement)",
    passif_par_travailleur:[{poste:"Sursalaire dimanche absent",montant_mensuel:"298 euros",montant_total_5ans:"17.880 euros"},{poste:"Sursalaire feries absent",montant_mensuel:"187 euros",montant_total_5ans:"11.220 euros"},{poste:"Indexation juil 2022 non appliquee (+3.22%)",montant_mensuel:"41 euros",montant_total_5ans:"2.460 euros"}],
    alertes:[{type:"CRITIQUE",titre:"Sursalaires dim/feries absents",detail:"Taux globalise 23.10euros/h. Aucun sursalaire +100% dim/feries sur taux base.",montant_estime:"485 euros/mois",base_legale:"Loi 16/03/1971 art.29",niveau:"LOI"},{type:"CRITIQUE",titre:"Indexation juil 2022 non appliquee",detail:"CCT CP 129 prevoyait +3.22% en juil 2022. Taux inchange depuis jan 2022.",montant_estime:"41 euros/mois",base_legale:"CP 129 indexation trimestrielle",niveau:"CP"}],
    points_conformes:["ONSS correct","Heures totales coherentes","Formation non verifiable sur fiche"],
    recommandations:["Appliquer indexation +3.22% juil 2022","Decomposer taux globalise","Ajouter sursalaires dim/feries"],
    note_contexte:"Premiere annee avec indexation significative. Taux non mis a jour.",_confidence:85}},
  {id:"simon2023",label:"Alain Simon",sub:"Semi-continu - Avr. 2023",tag:"RISQUE MODERE",tc:"#E67E22",score:55,ficheYear:2023,ficheMode:"retro",ficheType:"direct",
   analyse:{worker:{name:"Alain Simon",cp:"CP 129",regime:"Semi-continu 3 equipes",anciennete:"4 ans"},conformite_globale:"RISQUE MODERE",score:55,_year:2023,
    risque_financier_estime:"2.244 euros (ce travailleur uniquement)",
    passif_par_travailleur:[{poste:"Indexation jan 2023 non appliquee (+1.31%)",montant_mensuel:"21 euros",montant_total_5ans:"1.260 euros"},{poste:"Indexation juil 2023 non appliquee (+0.52%)",montant_mensuel:"8 euros",montant_total_5ans:"984 euros"}],
    alertes:[{type:"ATTENTION",titre:"Double indexation 2023 manquante",detail:"Taux 19.20 inchange. Attendu apres jan 2023: 19.45 et apres juil 2023: 19.55euros/h.",montant_estime:"29 euros/mois",base_legale:"CP 129 indexation trimestrielle",niveau:"CP"}],
    points_conformes:["Sursalaire dim correct","ONSS correct","Primes semi-continu presentes","Formation non verifiable sur fiche"],
    recommandations:["Corriger taux: 19.55euros/h","Regulariser ecart depuis jan 2023"],
    note_contexte:"Deux indexations manquantes en 2023. Montant modere mais cumulable.",_confidence:88}},
  {id:"dubois2025",label:"Thomas Dubois",sub:"Journee fixe - Sep. 2025",tag:"CONFORME",tc:"#1A7A4A",score:91,ficheYear:2025,ficheMode:"retro",ficheType:"direct",
   analyse:{worker:{name:"Thomas Dubois",cp:"CP 129",regime:"Journee fixe",anciennete:"2 ans"},conformite_globale:"CONFORME",score:91,_year:2025,
    risque_financier_estime:"0 euros - fiche conforme",passif_par_travailleur:[],
    alertes:[{type:"ATTENTION",titre:"Heures sup weekend a verifier",detail:"2h samedi sans mention sursalaire. Si volontaires: +50% obligatoire.",montant_estime:"a verifier",base_legale:"Loi 16/03/1971 art.29",niveau:"LOI"}],
    points_conformes:["Taux 15.80euros/h coherent avec indexations 2025","ONSS calcule correctement","Tickets 8euros conformes 2025","Formation non verifiable sur fiche"],
    recommandations:["Verifier nature heures samedi","Documenter si volontaires"],
    note_contexte:"Fiche globalement conforme. Un point de vigilance sur les heures samedi.",_confidence:92}},
  {id:"ernst2024",label:"Klaus Ernst",sub:"Continu 5 eq. - Aout 2024",tag:"NON CONFORME",tc:"#C0392B",score:25,ficheYear:2024,ficheMode:"retro",ficheType:"direct",
   analyse:{worker:{name:"Klaus Ernst",cp:"CP 129",regime:"Continu 5 equipes",anciennete:"19 ans"},conformite_globale:"NON CONFORME",score:25,_year:2024,
    risque_financier_estime:"52.320 euros (ce travailleur uniquement)",
    passif_par_travailleur:[{poste:"Coefficient anciennete 19 ans non applique",montant_mensuel:"312 euros",montant_total_5ans:"18.720 euros"},{poste:"Sursalaire dimanche absent",montant_mensuel:"331 euros",montant_total_5ans:"19.860 euros"},{poste:"Sursalaire feries absent",montant_mensuel:"198 euros",montant_total_5ans:"11.880 euros"},{poste:"Prime nuit sous-evaluee",montant_mensuel:"32 euros",montant_total_5ans:"1.860 euros"}],
    alertes:[{type:"CRITIQUE",titre:"Anciennete 19 ans non appliquee",detail:"Taux identique a un nouveau. Coef anciennete 15+ ans non repercute sur taux base.",montant_estime:"312 euros/mois",base_legale:"CCT Burgo art.4 anciennete",niveau:"CCT-ENTREPRISE"},{type:"CRITIQUE",titre:"Sursalaires dim/feries absents",detail:"Taux globalise. Aucun sursalaire +100% dim/feries.",montant_estime:"529 euros/mois",base_legale:"Loi 16/03/1971 art.29",niveau:"LOI"}],
    points_conformes:["ONSS correct","Heures totales coherentes"],
    recommandations:["Appliquer coef anciennete 19 ans","Decomposer taux globalise","Regulariser sursalaires"],
    note_contexte:"Travailleur senior avec anciennete mal appliquee. Passif eleve.",_confidence:87}},
  {id:"petit2025",label:"Marie Petit",sub:"Employes - Mar. 2025",tag:"RISQUE MODERE",tc:"#E67E22",score:62,ficheYear:2025,ficheMode:"retro",ficheType:"direct",
   analyse:{worker:{name:"Marie Petit",cp:"CP 129",regime:"Employe bureau",anciennete:"7 ans"},conformite_globale:"RISQUE MODERE",score:62,_year:2025,
    risque_financier_estime:"1.680 euros (ce travailleur uniquement)",
    passif_par_travailleur:[{poste:"Prime fin annee proratisee incorrectement",montant_mensuel:"58 euros",montant_total_5ans:"1.680 euros"}],
    alertes:[{type:"ATTENTION",titre:"Prime fin d annee mal calculee",detail:"Prime de 852 euros. Base calcul incorrecte: devrait inclure anciennete 7 ans selon CCT.",montant_estime:"58 euros/mois en equivalent",base_legale:"CCT Burgo art.7 prime fin annee",niveau:"CCT-ENTREPRISE"},{type:"ATTENTION",titre:"Cheque repas 8euros",detail:"CCT Burgo art.5 prevoit passage a 10euros au 01/06/2026. A anticiper.",montant_estime:"-",base_legale:"CCT Burgo 2025-2026 art.5",niveau:"CCT-ENTREPRISE"}],
    points_conformes:["Taux indexe correctement","Pecule vacances correct","ONSS employe correct","Formation non verifiable sur fiche"],
    recommandations:["Recalculer prime fin annee avec anciennete","Prevoir passage tickets 10euros juin 2026"],
    note_contexte:"Profil employe - regime different des ouvriers. Primes specifiques CCT.",_confidence:90}},
  {id:"adam2023",label:"Bernard Adam",sub:"Continu 5 eq. - Juin 2023",tag:"NON CONFORME",tc:"#C0392B",score:28,ficheYear:2023,ficheMode:"retro",ficheType:"direct",
   analyse:{worker:{name:"Bernard Adam",cp:"CP 129",regime:"Continu 5 equipes",anciennete:"23 ans"},conformite_globale:"NON CONFORME",score:28,_year:2023,
    risque_financier_estime:"48.960 euros (ce travailleur uniquement)",
    passif_par_travailleur:[{poste:"Heures sup base globalisee incorrecte",montant_mensuel:"187 euros",montant_total_5ans:"11.220 euros"},{poste:"Sursalaire dimanche absent",montant_mensuel:"322 euros",montant_total_5ans:"19.320 euros"},{poste:"Sursalaire feries absent",montant_mensuel:"198 euros",montant_total_5ans:"11.880 euros"},{poste:"Anciennete 23 ans non appliquee",montant_mensuel:"109 euros",montant_total_5ans:"6.540 euros"}],
    alertes:[{type:"CRITIQUE",titre:"Base heures sup incorrecte",detail:"Heures sup calculees sur taux globalise 24.10. Doivent l etre sur taux BASE uniquement x 1.5.",montant_estime:"187 euros/mois",base_legale:"Loi 16/03/1971 art.29",niveau:"LOI"},{type:"CRITIQUE",titre:"Anciennete 23 ans ignoree",detail:"Taux identique depuis 15+ ans. Coef maximal CCT non applique.",montant_estime:"109 euros/mois",base_legale:"CCT Burgo art.4",niveau:"CCT-ENTREPRISE"},{type:"CRITIQUE",titre:"Sursalaires dim/feries absents",detail:"Aucun sursalaire malgre 13h dim et 8h feries/mois.",montant_estime:"520 euros/mois",base_legale:"Loi 16/03/1971 art.29",niveau:"LOI"}],
    points_conformes:["ONSS correct","Volume heures coherent"],
    recommandations:["Recalculer heures sup sur taux base","Appliquer anciennete 23 ans","Ajouter sursalaires dim/feries"],
    note_contexte:"Travailleur tres ancien avec cumul d anomalies. Passif pres de 49k euros.",_confidence:86}},
  {id:"gerard2026preventif",label:"Laura Gerard",sub:"Semi-continu - Juil. 2026",tag:"CONFORME",tc:"#1A7A4A",score:94,ficheYear:2026,ficheMode:"preventif",ficheType:"direct",
   analyse:{worker:{name:"Laura Gerard",cp:"CP 129",regime:"Semi-continu 3 equipes",anciennete:"5 ans"},conformite_globale:"PRETE A EMETTRE",score:94,_year:2026,
    risque_financier_estime:"0 euros - fiche conforme",passif_par_travailleur:[],
    alertes:[],
    points_conformes:["Taux base 16.90euros/h coherent indexations 2026","Prime nuit 1.51euros/h presente (CCT n49)","Sursalaire dim sur taux base","Tickets 10euros conformes depuis juin 2026","Formation non verifiable sur fiche"],
    recommandations:["Maintenir ce niveau","Preparer deglobalisation jan 2027"],
    note_contexte:"Fiche conforme post-CCT n49. Bon exemple de mise en conformite 2026.",_confidence:95}},
  {id:"maes2027preventif",label:"Nicolas Maes",sub:"Employe senior - Fev. 2027",tag:"RISQUE MODERE",tc:"#E67E22",score:68,ficheYear:2027,ficheMode:"preventif",ficheType:"direct",
   analyse:{worker:{name:"Nicolas Maes",cp:"CP 129",regime:"Employe bureau",anciennete:"12 ans"},conformite_globale:"RISQUE MODERE",score:68,_year:2027,
    risque_financier_estime:"2.160 euros (ce travailleur uniquement)",
    passif_par_travailleur:[{poste:"Indexation jan 2027 non appliquee",montant_mensuel:"180 euros",montant_total_5ans:"2.160 euros"}],
    alertes:[{type:"ATTENTION",titre:"Indexation jan 2027 a confirmer",detail:"Taux employe 22.40euros/h inchange depuis 2026. Verifier si indexation CP 129 jan 2027 appliquee.",montant_estime:"a confirmer",base_legale:"CP 129 indexation trimestrielle",niveau:"CP"}],
    points_conformes:["Pecule vacances correct","Prime anciennete 12 ans presente","ONSS employe correct","Tickets 10euros conformes","Formation non verifiable sur fiche"],
    recommandations:["Verifier et appliquer indexation jan 2027","Confirmer taux avec secretariat social"],
    note_contexte:"Employe senior globalement conforme. Un point d indexation a verifier.",_confidence:89}},
  {id:"collin2022",label:"Pierre Collin",sub:"Journee fixe - Mar. 2022",tag:"CONFORME",tc:"#1A7A4A",score:88,ficheYear:2022,ficheMode:"retro",ficheType:"direct",
   analyse:{worker:{name:"Pierre Collin",cp:"CP 129",regime:"Journee fixe",anciennete:"1 an"},conformite_globale:"CONFORME",score:88,_year:2022,
    risque_financier_estime:"0 euros - fiche conforme",passif_par_travailleur:[],
    alertes:[{type:"ATTENTION",titre:"Formation 2022",detail:"Obligation formation pas encore en vigueur en 2022 (Deal emploi oct 2022). Aucune anomalie.",montant_estime:"-",base_legale:"Loi Deal emploi 03/10/2022",niveau:"LOI"}],
    points_conformes:["Taux 14.20euros/h coherent 2022 avant indexation juil","ONSS correct","Heures normales conformes","Pas d obligation formation avant oct 2022"],
    recommandations:["Verifier application indexation juil 2022 sur fiches suivantes"],
    note_contexte:"Fiche debut 2022 avant indexations. Conforme pour la periode.",_confidence:91}},
  {id:"baert2024",label:"Sofie Baert",sub:"Continu 5 eq. - Jan. 2024",tag:"NON CONFORME",tc:"#C0392B",score:30,ficheYear:2024,ficheMode:"retro",ficheType:"direct",
   analyse:{worker:{name:"Sofie Baert",cp:"CP 129",regime:"Continu 5 equipes",anciennete:"6 ans"},conformite_globale:"NON CONFORME",score:30,_year:2024,
    risque_financier_estime:"39.840 euros (ce travailleur uniquement)",
    passif_par_travailleur:[{poste:"Sursalaire dimanche absent",montant_mensuel:"322 euros",montant_total_5ans:"19.320 euros"},{poste:"Sursalaire feries absent",montant_mensuel:"198 euros",montant_total_5ans:"11.880 euros"},{poste:"Indexation mai 2024 non appliquee (+2.12%)",montant_mensuel:"37 euros",montant_total_5ans:"444 euros"},{poste:"Prime nuit sous-evaluee",montant_mensuel:"69 euros",montant_total_5ans:"828 euros"},{poste:"Base heures sup incorrecte",montant_mensuel:"12 euros",montant_total_5ans:"144 euros"}],
    alertes:[{type:"CRITIQUE",titre:"Sursalaires dim/feries absents",detail:"Taux globalise. 13h dim + 8h feries sans sursalaire +100%.",montant_estime:"520 euros/mois",base_legale:"Loi 16/03/1971 art.29",niveau:"LOI"},{type:"CRITIQUE",titre:"Indexation mai 2024 non appliquee",detail:"CCT CP 129 +2.12% depuis mai 2024. Taux inchange depuis 2023.",montant_estime:"37 euros/mois",base_legale:"CP 129 indexation trimestrielle",niveau:"CP"},{type:"ATTENTION",titre:"Prime nuit sous-evaluee",detail:"Prime nuit semaine 3.50euros/h. CCT Burgo prevoit 4.0209euros/h.",montant_estime:"69 euros/mois",base_legale:"CCT Burgo art.3 primes equipe",niveau:"CCT-ENTREPRISE"}],
    points_conformes:["ONSS correct","Volume heures coherent"],
    recommandations:["Appliquer indexation +2.12% mai 2024","Decomposer taux globalise","Corriger prime nuit a 4.0209euros/h"],
    note_contexte:"Fiche jan 2024. Indexation mai 2024 pas encore due mais taux de base deja sous-evalue.",_confidence:88}},
    {id:"hugo2025interim",label:"Adam Hugo",sub:"CP 322 Randstad - Jan-Juin 2026",tag:"VERIFICATION REQUISE",tc:"#E67E22",score:65,ficheYear:2026,ficheMode:"retro",ficheType:"interim",
   analyse:{worker:{name:"Adam Hugo",cp:"CP 322",regime:"Ouvrier production interim - qualification variable (standard + massicot)",anciennete:"4 ans (depuis 05/04/2022)"},conformite_globale:"RISQUE MODERE",score:65,_year:2026,
    risque_financier_estime:"4.83 a 14.32 euros (jan-juin 2026) - a confirmer selon poste occupe",
    passif_par_travailleur:[
      {poste:"Sem 21 mai (19-22/05): P10 4h sur taux 19.5568 alors que taux 21.9738 present",montant_mensuel:"4.83 euros si poste massicot confirme",montant_total_5ans:"a calculer sur historique complet"},
      {poste:"Sem 04 janv (21/01): P10 8h sur taux 19.1940 - poste a confirmer",montant_mensuel:"0 si standard / 9.49 si massicot",montant_total_5ans:"a confirmer"},
    ],
    alertes:[
      {type:"ATTENTION",titre:"VERIFICATION REQUISE - Poste non mentionne sur la fiche",detail:"CP 322 exige que la qualification professionnelle soit identifiable. La mention 'selon grille client' est insuffisante. Demander a Randstad confirmation ecrite du poste occupe chaque semaine avec P10.",montant_estime:"-",base_legale:"CP 322 - identification qualification professionnelle",niveau:"CP"},
      {type:"ATTENTION",titre:"Sem 21 mai: P10 sur taux de base alors que taux massicot present",detail:"4h P10 calculees sur 19.5568euros/h. Le taux massicot 21.9738euros/h est present cette semaine. Si poste massicot confirme: ecart = 4h x (21.9738-19.5568) x 50% = 4.83euros. A verifier: confirmer la qualification professionnelle du travailleur cette semaine cette semaine?",montant_estime:"4.83 euros si confirme",base_legale:"Loi 16/03/1971 art.29 - heures sup sur taux reel du poste",niveau:"LOI"},
      {type:"ATTENTION",titre:"Sem 04 janv: P10 sur taux 19.1940 - poste inconnu",detail:"8h P10 calculees sur 19.1940euros/h (taux standard). Si la qualification massicot est confirmee pour cette semaine (21.5662euros/h): ecart = 8h x (21.5662-19.1940) x 50% = 9.49euros. A verifier: confirmer la qualification professionnelle du travailleur cette semaine le 21/01/2026?",montant_estime:"0 a 9.49 euros selon poste",base_legale:"Loi 16/03/1971 art.29",niveau:"LOI"},
    ],
    points_conformes:[
      "Sem 18 avril (30/04): P10 correctement calcule sur taux massicot 21.5662euros/h",
      "Sursalaires weekend/feries presents et corrects (P08, P06)",
      "Primes equipe decomposees (P00, P01, P02, P52, P54, P03)",
      "ONSS calcule correctement sur salaire brut x 108% x 13.07%",
      "Cheques repas 8euros conformes 2026 (passage 10euros prevu juin 2026)",
      "Frais domicile-travail presentes",
      "Correction fiche sem 05 effectuee correctement (fiche sem 11)",
    ],
    recommandations:[
      "Solliciter aupres de Randstad (04/2421030) une attestation ecrite de la qualification professionnelle pour les semaines avec heures supplementaires (sem 21 mai et sem 04 janv)",
      "Si qualification massicot confirmee sem 21 mai: regulariser 4.83 euros",
      "Si qualification massicot confirmee sem 04 janv: regulariser complement jusqu a 14.32 euros au total",
      "Exiger de l agence la mention explicite de la qualification professionnelle sur chaque ligne de prestation (obligation CP 322)",
      "Conserver ce rapport comme base de discussion",
    ],
    note_contexte:"Analyse basee sur 6 fiches jan-juin 2026 (sem 05, 09, 11, 14, 18, 22). 3 semaines avec P10 identifiees. 1 correcte (sem 18 avril), 2 a verifier selon poste. La non-mention du poste sur la fiche est elle-meme une anomalie CP 322.",_confidence:78}},
];

